package com.example

import groovy.sql.Sql

import javax.sql.DataSource

class BootStrap {

    DataSource dataSource_secondary  // Spring injects the secondary datasource bean

    def init = {
        // Set tenant for DISCRIMINATOR multi-tenancy
        System.setProperty('gorm.tenantId', 'tenant1')

        // Manually create the METRIC table on the secondary database.
        // GORM's dbCreate only creates tables on the datasource declared in the
        // domain's mapping block. Since Metric is on the default datasource,
        // we need to create the table structure on secondary manually so we can
        // test whether Data Service routing actually sends data there.
        def secondarySql = new Sql(dataSource_secondary)
        secondarySql.execute('''
            CREATE TABLE IF NOT EXISTS METRIC (
                ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                VERSION BIGINT NOT NULL,
                NAME VARCHAR(255) NOT NULL,
                "VALUE" DOUBLE PRECISION NOT NULL,
                DATE_CREATED TIMESTAMP
            )
        ''')
        secondarySql.close()
        println 'BootStrap: Created METRIC table on secondary database'

        println ''
        println '=' * 60
        println 'Auto-Implemented Data Service CRUD Routing Bug Demo'
        println '=' * 60
        println ''
        println 'Visit http://localhost:8080/bugDemo/index to see the bug'
        println ''
        println 'This app has two H2 in-memory datasources:'
        println '  Primary:   jdbc:h2:mem:primarydb   (METRIC + ITEM tables via dbCreate)'
        println '  Secondary: jdbc:h2:mem:secondarydb (METRIC table, manually created)'
        println ''
        println 'Two Data Service patterns tested:'
        println '  Pattern 1: MetricService (abstract class with @Transactional(connection = "secondary"))'
        println '  Pattern 2: MetricInterfaceOnlyDataService (interface-only, no abstract class)'
        println 'Auto-implemented save()/count() SHOULD route to secondary.'
        println ''
        println 'The /bugDemo/index endpoint will:'
        println '  1. Save Metrics via both Data Service patterns'
        println '  2. Query both databases via raw JDBC'
        println '  3. Report which database the data actually ended up in'
        println '=' * 60
    }

    def destroy = {
    }

}
